"""Phase 3 — football-data.co.uk team-match ingestion.

For each configured league x season, read the results CSV and upsert one `fixtures`
row plus the two `team_match` rows (home + away perspective). Idempotent: re-running
upserts in place via the natural fixture key and the (fixture_id, team_id) key.
Derived columns (clean_sheet/btts/total_goals/result) are generated by Postgres.

Run:  python -m ingestion.team_match
"""

from __future__ import annotations

import datetime as dt

import pandas as pd
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from app.db import SessionLocal
from app.models.facts import Fixture, TeamMatch
from app.models.reference import Competition, Team
from ingestion.fdcouk import read_results
from ingestion.names import clean_name
from ingestion.teams import resolve_fdcouk_team

# 6 seasons: 2020-21 .. 2025-26
BACKFILL_SEASONS = ["2021", "2122", "2223", "2324", "2425", "2526"]

# team_match field -> football-data.co.uk column, per perspective
HOME_MAP = {
    "gf": "FTHG", "ga": "FTAG", "shots": "HS", "sot": "HST",
    "shots_conceded": "AS", "sot_conceded": "AST", "fouls": "HF",
    "corners": "HC", "yellows": "HY", "reds": "HR",
}
AWAY_MAP = {
    "gf": "FTAG", "ga": "FTHG", "shots": "AS", "sot": "AST",
    "shots_conceded": "HS", "sot_conceded": "HST", "fouls": "AF",
    "corners": "AC", "yellows": "AY", "reds": "AR",
}
_METRIC_FIELDS = list(HOME_MAP.keys())


class CorrectionError(Exception):
    """A registered CSV correction no longer matches exactly one CSV row."""


# Known-wrong football-data.co.uk cells, overridden at ingest so re-running the
# backfill can never reinstate them. Each entry was found by cross-validating
# FBref-parsed corners against fd.co.uk (2026-07-03, see docs/adr/0008 corners
# update) and independently confirmed by a third source (ESPN/Opta) before
# being registered — FBref alone is NOT sufficient evidence (its Blackburn v
# Birmingham 2324 corners are wrong where fd.co.uk is right).
# Key: (fdcouk_key, season, HomeTeam, AwayTeam) exactly as in the CSV.
CSV_CORRECTIONS: dict[tuple[str, str, str, str], dict[str, int]] = {
    # ESPN: Arsenal 13-3 Burnley; CSV says 3-3 (dropped digit).
    ("E0", "2324", "Arsenal", "Burnley"): {"HC": 13},
    # ESPN: Everton 4, Man City 8; CSV has home/away swapped.
    ("E0", "2324", "Everton", "Man City"): {"HC": 4, "AC": 8},
    #
    # --- 2026-08-24 sweep: every league Fixture where fd.co.uk and FBref's
    # player-sums disagreed by 5+ on a metric, with ESPN as arbiter. Only
    # recorded where TWO sources agree against the third; smaller gaps (2-4)
    # are deliberately NOT corrected — at that size FBref is wrong about as
    # often as fd.co.uk, so a majority vote stops being evidence.
    #
    ("E0", "2021", "Crystal Palace", "Leeds"): {"AF": 16},   # Leeds fouls 1
    ("E0", "2021", "Man United", "Aston Villa"): {"AS": 15},  # Villa shots 5
    ("E1", "2021", "Bournemouth", "Middlesbrough"): {"HF": 14},  # fouls 4
    ("E0", "2021", "Leeds", "Liverpool"): {"HF": 7},          # Leeds fouls 17
    ("E0", "2122", "Newcastle", "West Ham"): {"AS": 18},      # shots 8
    ("E0", "2122", "West Ham", "Leicester"): {"HS": 19},      # shots 13
    ("E0", "2122", "Aston Villa", "Tottenham"): {"HS": 19},   # shots 9
    ("E1", "2223", "Bristol City", "Huddersfield"): {"AF": 3},  # fouls 13
    ("E0", "2223", "Aston Villa", "Leeds"): {"AF": 18},       # Leeds fouls 8
    ("E1", "2324", "Bristol City", "Birmingham"): {"HS": 9},  # shots 19
    ("E1", "2324", "Huddersfield", "Cardiff"): {"AF": 10},    # Cardiff fouls 19
    ("E1", "2324", "Birmingham", "Sheffield Weds"): {"AY": 5},  # yellows 0
    ("E1", "2324", "Blackburn", "QPR"): {"AS": 17},           # QPR shots 7
    ("E1", "2324", "Leeds", "Hull"): {"HF": 9},               # Leeds fouls 19
    ("E0", "2425", "Everton", "Bournemouth"): {"AF": 11},     # fouls 1
    ("E0", "2425", "Man United", "Brentford"): {"HF": 4},     # fouls 14
    ("E0", "2425", "Arsenal", "Nott'm Forest"): {"AF": 11},   # fouls 1
    #
    # --- CROSSED FIXTURES. fd.co.uk published one match's whole event block
    # against another's. Goals and corners were unaffected in the 2324 pair
    # (its corner cells were already corrected below), which is why this went
    # unnoticed: only the shots/SoT/fouls/cards block moved.
    #
    # 2023-10-28: Hull v Preston carries Watford v Millwall's figures VERBATIM
    # — confirmed in the raw CSV, so this is upstream, not our ingest.
    ("E1", "2324", "Hull", "Preston"): {
        "HC": 2, "AC": 11,
        "HS": 11, "HST": 2, "HF": 8,
        "AS": 7, "AST": 1, "AF": 20, "AY": 4,
    },
    # Final-day 2526: these two matches' values are SWAPPED with each other
    # (not duplicated), which is why a duplicate scan cannot see them — only
    # cross-source comparison can. Corners were caught first; the rest of the
    # block was still crossed until this sweep.
    ("E0", "2526", "Sunderland", "Chelsea"): {
        "HC": 6, "AC": 2,
        "HS": 21, "HST": 6, "HY": 5,
        "AS": 8, "AST": 3, "AF": 12, "AY": 3, "AR": 1,
    },
    ("E0", "2526", "Tottenham", "Everton"): {
        "HC": 7, "AC": 7,
        "HS": 20, "HST": 2, "HY": 3,
        "AS": 10, "AST": 1, "AF": 18, "AY": 2, "AR": 0,
    },
}


def apply_csv_corrections(df: pd.DataFrame, fdcouk_key: str, season: str) -> pd.DataFrame:
    """Override known-bad cells in one league-season's results CSV.

    Applied to the raw row so both team perspectives (HOME_MAP/AWAY_MAP) ingest
    the corrected value. Fails loud if a registered correction matches anything
    other than exactly one row — a rename/reshape upstream must not silently
    stop a correction applying.
    """
    for (key, ssn, home, away), fixes in CSV_CORRECTIONS.items():
        if (key, ssn) != (fdcouk_key, season):
            continue
        mask = (df["HomeTeam"] == home) & (df["AwayTeam"] == away)
        n = int(mask.sum())
        if n != 1:
            raise CorrectionError(
                f"correction {key}/{ssn} {home} v {away} matched {n} CSV rows"
            )
        for col, value in fixes.items():
            df.loc[mask, col] = value
    return df


def _to_int(value) -> int | None:
    """football-data stat cells are floats/blanks — coerce to int or None."""
    try:
        if value is None or pd.isna(value):
            return None
        return int(value)
    except (ValueError, TypeError):
        return None


def _parse_kickoff(date_str, time_str) -> dt.datetime | None:
    """Parse DD/MM/YYYY (+ optional HH:MM) to a UTC-aware datetime."""
    d = pd.to_datetime(str(date_str), dayfirst=True, errors="coerce")
    if pd.isna(d):
        return None
    if time_str is not None and str(time_str).strip() not in ("", "nan"):
        t = pd.to_datetime(str(time_str), errors="coerce")
        if not pd.isna(t):
            d = d.replace(hour=int(t.hour), minute=int(t.minute))
    return d.to_pydatetime().replace(tzinfo=dt.timezone.utc)


def _team_cache(session: Session) -> dict[str, int]:
    return {
        name: tid
        for name, tid in session.execute(
            select(Team.fdcouk_name, Team.id)
        ).all()
        if name
    }


def _team_id(session: Session, cache: dict[str, int], name: str) -> int:
    cn = clean_name(name)
    if cn not in cache:
        cache[cn] = resolve_fdcouk_team(session, cn).id
    return cache[cn]


def ingest_competition_season(
    session: Session, competition: Competition, season: str, cache: dict[str, int]
) -> int:
    """Upsert all fixtures + team_match rows for one league-season. Returns fixtures."""
    df = apply_csv_corrections(
        read_results(season, competition.fdcouk_key), competition.fdcouk_key, season
    )
    has_time = "Time" in df.columns
    n = 0
    for _, row in df.iterrows():
        kickoff = _parse_kickoff(row.get("Date"), row.get("Time") if has_time else None)
        if kickoff is None:
            continue
        home_id = _team_id(session, cache, row["HomeTeam"])
        away_id = _team_id(session, cache, row["AwayTeam"])

        fixture_id = session.execute(
            insert(Fixture)
            .values(
                competition_id=competition.id,
                season=season,
                date=kickoff,
                home_team_id=home_id,
                away_team_id=away_id,
                status="finished",
            )
            .on_conflict_do_update(
                constraint="uq_fixture_natural",
                set_={"date": kickoff, "status": "finished"},
            )
            .returning(Fixture.id)
        ).scalar_one()

        for team_id, opp_id, is_home, cmap in (
            (home_id, away_id, True, HOME_MAP),
            (away_id, home_id, False, AWAY_MAP),
        ):
            vals = {
                "fixture_id": fixture_id,
                "competition_id": competition.id,
                "competition_type": "club_league",
                "season": season,
                "date": kickoff,
                "team_id": team_id,
                "opponent_id": opp_id,
                "is_home": is_home,
                # docs/adr/0015. football-data.co.uk is the historical
                # authority, so it RECLAIMS a Fixture ESPN wrote earlier —
                # `source` is in the update set precisely so the row stops
                # claiming to be ESPN's when that happens.
                "source": "fdcouk",
                **{field: _to_int(row.get(col)) for field, col in cmap.items()},
            }
            session.execute(
                insert(TeamMatch)
                .values(**vals)
                .on_conflict_do_update(
                    constraint="uq_team_match",
                    set_={k: vals[k] for k in (["date", "source"] + _METRIC_FIELDS)},
                )
            )
        n += 1
    return n


def ingest(seasons: list[str] = BACKFILL_SEASONS) -> dict:
    report: dict[str, int] = {}
    skipped: list[str] = []
    with SessionLocal() as session:
        comps = list(
            session.scalars(
                select(Competition).where(Competition.fdcouk_key.is_not(None))
            )
        )
        cache = _team_cache(session)
        for comp in comps:
            for season in seasons:
                try:
                    n = ingest_competition_season(session, comp, season, cache)
                    session.commit()
                    report[f"{comp.name} {season}"] = n
                except Exception as exc:  # network/parse — skip this league-season
                    session.rollback()
                    cache = _team_cache(session)  # drop phantom (rolled-back) ids
                    skipped.append(f"{comp.fdcouk_key}/{season}: {type(exc).__name__}: {exc}")
        fixtures = session.query(Fixture).count()
        team_rows = session.query(TeamMatch).count()
    return {"per_league_season": report, "skipped": skipped,
            "fixtures": fixtures, "team_match": team_rows}


if __name__ == "__main__":
    r = ingest()
    print(f"fixtures: {r['fixtures']}   team_match: {r['team_match']}   "
          f"(expect team_match == 2 x fixtures: {r['team_match'] == 2 * r['fixtures']})")
    if r["skipped"]:
        print("skipped:", r["skipped"])
    print("per league-season fixtures:")
    for k, v in r["per_league_season"].items():
        print(f"  {k}: {v}")
