"""Phase 3 — football-data.co.uk team-match ingestion.

For each configured league x season, read the results CSV and upsert one `fixtures`
row plus the two `team_match` rows (home + away perspective). Idempotent: re-running
upserts in place via the natural fixture key and the (fixture_id, team_id) key.
Derived columns (clean_sheet/btts/total_goals/result) are generated by Postgres.

Run:  python -m ingestion.team_match
"""

from __future__ import annotations

import datetime as dt

import pandas as pd
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from app.db import SessionLocal
from app.models.facts import Fixture, TeamMatch
from app.models.reference import Competition, Team
from ingestion.fdcouk import read_results
from ingestion.names import clean_name
from ingestion.teams import resolve_fdcouk_team

# 6 seasons: 2020-21 .. 2025-26
BACKFILL_SEASONS = ["2021", "2122", "2223", "2324", "2425", "2526"]

# team_match field -> football-data.co.uk column, per perspective
HOME_MAP = {
    "gf": "FTHG", "ga": "FTAG", "shots": "HS", "sot": "HST",
    "shots_conceded": "AS", "sot_conceded": "AST", "fouls": "HF",
    "corners": "HC", "yellows": "HY", "reds": "HR",
}
AWAY_MAP = {
    "gf": "FTAG", "ga": "FTHG", "shots": "AS", "sot": "AST",
    "shots_conceded": "HS", "sot_conceded": "HST", "fouls": "AF",
    "corners": "AC", "yellows": "AY", "reds": "AR",
}
_METRIC_FIELDS = list(HOME_MAP.keys())


def _to_int(value) -> int | None:
    """football-data stat cells are floats/blanks — coerce to int or None."""
    try:
        if value is None or pd.isna(value):
            return None
        return int(value)
    except (ValueError, TypeError):
        return None


def _parse_kickoff(date_str, time_str) -> dt.datetime | None:
    """Parse DD/MM/YYYY (+ optional HH:MM) to a UTC-aware datetime."""
    d = pd.to_datetime(str(date_str), dayfirst=True, errors="coerce")
    if pd.isna(d):
        return None
    if time_str is not None and str(time_str).strip() not in ("", "nan"):
        t = pd.to_datetime(str(time_str), errors="coerce")
        if not pd.isna(t):
            d = d.replace(hour=int(t.hour), minute=int(t.minute))
    return d.to_pydatetime().replace(tzinfo=dt.timezone.utc)


def _team_cache(session: Session) -> dict[str, int]:
    return {
        name: tid
        for name, tid in session.execute(
            select(Team.fdcouk_name, Team.id)
        ).all()
        if name
    }


def _team_id(session: Session, cache: dict[str, int], name: str) -> int:
    cn = clean_name(name)
    if cn not in cache:
        cache[cn] = resolve_fdcouk_team(session, cn).id
    return cache[cn]


def ingest_competition_season(
    session: Session, competition: Competition, season: str, cache: dict[str, int]
) -> int:
    """Upsert all fixtures + team_match rows for one league-season. Returns fixtures."""
    df = read_results(season, competition.fdcouk_key)
    has_time = "Time" in df.columns
    n = 0
    for _, row in df.iterrows():
        kickoff = _parse_kickoff(row.get("Date"), row.get("Time") if has_time else None)
        if kickoff is None:
            continue
        home_id = _team_id(session, cache, row["HomeTeam"])
        away_id = _team_id(session, cache, row["AwayTeam"])

        fixture_id = session.execute(
            insert(Fixture)
            .values(
                competition_id=competition.id,
                season=season,
                date=kickoff,
                home_team_id=home_id,
                away_team_id=away_id,
                status="finished",
            )
            .on_conflict_do_update(
                constraint="uq_fixture_natural",
                set_={"date": kickoff, "status": "finished"},
            )
            .returning(Fixture.id)
        ).scalar_one()

        for team_id, opp_id, is_home, cmap in (
            (home_id, away_id, True, HOME_MAP),
            (away_id, home_id, False, AWAY_MAP),
        ):
            vals = {
                "fixture_id": fixture_id,
                "competition_id": competition.id,
                "competition_type": "club_league",
                "season": season,
                "date": kickoff,
                "team_id": team_id,
                "opponent_id": opp_id,
                "is_home": is_home,
                **{field: _to_int(row.get(col)) for field, col in cmap.items()},
            }
            session.execute(
                insert(TeamMatch)
                .values(**vals)
                .on_conflict_do_update(
                    constraint="uq_team_match",
                    set_={k: vals[k] for k in (["date"] + _METRIC_FIELDS)},
                )
            )
        n += 1
    return n


def ingest(seasons: list[str] = BACKFILL_SEASONS) -> dict:
    report: dict[str, int] = {}
    skipped: list[str] = []
    with SessionLocal() as session:
        comps = list(
            session.scalars(
                select(Competition).where(Competition.fdcouk_key.is_not(None))
            )
        )
        cache = _team_cache(session)
        for comp in comps:
            for season in seasons:
                try:
                    n = ingest_competition_season(session, comp, season, cache)
                    session.commit()
                    report[f"{comp.name} {season}"] = n
                except Exception as exc:  # network/parse — skip this league-season
                    session.rollback()
                    cache = _team_cache(session)  # drop phantom (rolled-back) ids
                    skipped.append(f"{comp.fdcouk_key}/{season}: {type(exc).__name__}: {exc}")
        fixtures = session.query(Fixture).count()
        team_rows = session.query(TeamMatch).count()
    return {"per_league_season": report, "skipped": skipped,
            "fixtures": fixtures, "team_match": team_rows}


if __name__ == "__main__":
    r = ingest()
    print(f"fixtures: {r['fixtures']}   team_match: {r['team_match']}   "
          f"(expect team_match == 2 x fixtures: {r['team_match'] == 2 * r['fixtures']})")
    if r["skipped"]:
        print("skipped:", r["skipped"])
    print("per league-season fixtures:")
    for k, v in r["per_league_season"].items():
        print(f"  {k}: {v}")
